FROM golang

VOLUME /go

ADD server/ /go/src/github.com/karolhor/go-workshops-challange/server/
ADD clients/ /go/src/github.com/karolhor/go-workshops-challange/clients/
ADD common/ /go/src/github.com/karolhor/go-workshops-challange/common/

WORKDIR /
ADD Makefile /
CMD ["make", "buildgo"]
